### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by obutuz** [arkrayBergonia/Python-ImageScrapper#1]
Hye. I get  "TypeError: not all arguments converted during string formatting" . when I try to run the scrapeGoogleImages code

**Comment by obutuz** [comment]
[2019-10-22 22:48:56,687 INFO scrapeGoogleImages]: Extracting image links
Traceback (most recent call last):
  File "scrapeGoogleImages.py", line 88, in <module>
    main()
  File "scrapeGoogleImages.py", line 85, in main
    run(args.search, args.directory, args.num_images)
  File "scrapeGoogleImages.py", line 74, in run
    images = extract_images(query, num_images)
  File "scrapeGoogleImages.py", line 43, in extract_images
    url = get_query_url(query)
  File "scrapeGoogleImages.py", line 34, in get_query_url
    return "https://www.google.co.in/search?q=number+plate+&oq=number+plate&source=lnms&tbm=isch" % query
TypeError: not all arguments converted during string formatting
